force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradeUtil.cls
/*
* @description: Class for Trade__c object methods
* @author: jmruizperez1999@gmail.com
* @date: 01/07/2022
* @class: TradeUtil
* @test: TradeUtilTest
*/
public class TradeUtil {
    /*
    * @description: Method that query Trade__c object by fields
    * @author: jmruizperez1999@gmail.com
    * @date: 01/07/2022
    * @param: List<String> fields to query
    * @return: List<Trade__c> Trade list
    */
    public static List<Trade__c> getAllRecordsByFields(List<String> fields){
        try{
            if(fields != null){
                return Database.query('SELECT ' + string.join(fields,',') + ' FROM Trade__c');
            }else{
                return Database.query('SELECT ID FROM Trade__c');
            }
        }catch(Exception ex){
            System.debug('The following exception has occurred: ' + ex.getMessage());
            return null;
        }
    }

    /*
    * @description: Method that creates a new Trade__c object in Database
    * @author: jmruizperez1999@gmail.com
    * @date: 02/07/2022
    * @return: Boolean True if OK False if NOT OK
    */
    public static Boolean saveNewTrade(String sellCcy, Decimal sellAmnt, String buyCcy, Decimal rate){
        try{

            Trade__c trade = new Trade__c();
            trade.Sell_Currency__c = sellCcy;
            trade.Sell_Amount__c = sellAmnt;
            trade.Rate__c = rate;
            trade.Buy_Currency__c = buyCcy;

            insert trade;
            return true;
        }catch(Exception ex){
            System.debug('Exception: ' + ex.getMessage());
            return false;
        }
    }
}