force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <formula>Sell_Amount__c * Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradeManagementController.cls
/*
* @description: Controller class of tradeManagement LWC
* @author: jmruizperez1999@gmail.com
* @date: 01/07/2022
* @class: TradeManagementController
* @test: TradeManagementControllerTest
*/
public class TradeManagementController {
    /*
    * @description: Method that get all trades from database
    * @author: jmruizperez1999@gmail.com
    * @date: 01/07/2022
    * @return: List<Trade__c> Trade list
    */
    @AuraEnabled
    public static List<Trade__c> getTrades(){
        try{
            return TradeUtil.getAllRecordsByFields(new List<String>{
                                                    'Sell_Currency__c', 
                                                    'Sell_Amount__c', 
                                                    'Rate__c',
                                                    'Buy_Currency__c',
                                                    'Buy_Amount__c',
                                                    'Date_Booked__c'});
        }catch(Exception ex){
            System.debug('Exception: ' + ex.getMessage());
            return null;
        }
    }

    /*
    * @description: Method that receive a new Trade from LWC and call Util class to save it.
    * @author: jmruizperez1999@gmail.com
    * @date: 02/07/2022
    * @return: Boolean True if OK False if NOT OK
    */
    @AuraEnabled
    public static Boolean createTrade(String sellCcy, Decimal sellAmnt, String buyCcy, Decimal rate){
        try{
            return TradeUtil.saveNewTrade(sellCcy, sellAmnt, buyCcy, rate);
        }catch(Exception ex){
            System.debug('Exception: ' + ex.getMessage());
            return false;
        }
    }
}