force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradeManagementControllerTest.cls
/*
* @author: jmruizperez1999@gmail.com
* @date: 01/07/2021
* @class: TradeManagementControllerTest
*/
@isTest
public class TradeManagementControllerTest {
    @testSetup static void setup() {
        Trade__c trade = new Trade__c();
        trade.Buy_Currency__c = 'USD';
        trade.Rate__c = 1.2323;
        trade.Sell_Amount__c = 500.12;
        trade.Sell_Currency__c = 'GBP';
        insert trade;
    }
    @isTest
    static void testGetTrades(){
        System.assertEquals(1, TradeManagementController.getTrades().size());
    }

    @isTest
    static void testCreateTrade(){
        System.assertEquals(true, TradeManagementController.createTrade('GBP', 100, 'EUR', 1.2345));
    }
}